services:
  - type: web
    name: audiobook-django-app
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
      pip install -r requirements.txt
    startCommand: gunicorn audio_books_project.wsgi:application --bind 0.0.0.0:$PORT
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PATH
        value: bin:$PATH
