services:
  - type: web
    name: audiobook-django-app
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Убираем colors.sh
      if [ -f /home/render/colors.sh ]; then rm /home/render/colors.sh || true; fi
      chmod +x build.sh
      ./build.sh
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn audio_books_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PATH
        value: "bin:$PATH"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "audiobook-django-app.onrender.com"
