# Generated by Django 5.2.3 on 2025-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text_field',
            field=models.TextField(blank=True),
        ),
    ]
