# Generated by Django 5.2.3 on 2025-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_pagerange_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf_file',
            new_name='pdf_url',
        ),
        migrations.AlterField(
            model_name='bookaudiopart',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookaudiopart',
            name='end_page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookaudiopart',
            name='start_page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pagerange',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
