# Generated by Django 5.2.3 on 2025-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_conversationtext_remove_book_text_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationtext',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='conversationtext',
            name='title',
        ),
        migrations.AddField(
            model_name='conversationtext',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
