services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn audio_books_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: audio_books_project.settings