services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn audio_books_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DjangoProject
          property: connectionString
